services:
  redis:
    image: redis:7.4.2-alpine  # 기본 이미지를 사용하지만, 빌드를 명시적으로 추가
    container_name: redis-server
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_dev_data:/data
    command: [ "redis-server", "--appendonly", "yes", "--appendfsync", "everysec" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  stockassist:
    build:
      context: ./
    image: 46112/tuzain:latest  # 이미지를 새로 빌드하거나 해당 이미지를 사용
    container_name: stockassist-server
    restart: always
    ports:
      - 4003:4003
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CRAWLING_DB_URL=${CRAWLING_DB_URL}
      - CRAWLING_DB_USER=${CRAWLING_DB_USER}
      - CRAWLING_DB_PASSWORD=${CRAWLING_DB_PASSWORD}
      - GMAIL_USERNAME=${GMAIL_USERNAME}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - KIS_APP_KEY=${KIS_APP_KEY}
      - KIS_APP_SECRET=${KIS_APP_SECRET}
      - KIS_CANO=${KIS_CANO}
      - KIS_ACNT_PRDT_CD=${KIS_ACNT_PRDT_CD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_dev_data:
    external: true
